window.CAROL_SONG_DATA = {
  "en": {
    "$schema": "../song-language.schema.json",
    "language": "en",
    "htmlLang": "en",
    "indexFile": "index.html",
    "churchName": "Thuruthicadu Mar Thoma Church",
    "collectionTitle": "Carol Rounds Songs",
    "description": "Carol Rounds songs from Thuruthicadu Mar Thoma Church",
    "fontClass": "",
    "songs": [
      {
        "slug": "aadi-aadi-paduvaan",
        "title": "Aadi Aadi Paaduvaanayi",
        "listLabel": "Aadi Aadi Paaduvaanayi",
        "order": 16,
        "lines": [
          "Aadi Aadi Paaduvaanayi",
          "Naattil Kondaaduvaan",
          "A. A. Aaa...",
          "Aadi Aadi Paaduvaanayi",
          "Naattil Kondaaduvaan",
          "Veeduthorum Nammalellam Thulliyaadi Pokanam (2)",
          "",
          "Vannallo Shaanthi Poyallo Shantakal (2)",
          "Illaallo Malsaram Naam Onnaayi Paaduvaan",
          "Naam Onnaayi Paaduvaan",
          "",
          "(Aadi Aadi Paaduvaanayi...)",
          "",
          "Raajaadhi Raajan Bethlehem Goshalee (2)",
          "Bhoojaatham Cheythathaam Vaarthayai Paaduvaan",
          "Vaarthayai Paaduvaan",
          "",
          "(Aadi Aadi Paaduvaanayi...)"
        ]
      },
      {
        "slug": "aanandham-aanandham",
        "title": "Aanadam Aanadam Aaha Maanavare",
        "listLabel": "Aanadam Aanadam Aaha Maanavare",
        "order": 12,
        "lines": [
          "Aanadam Aanadam Aaha Maanavare",
          "Swarlokarellam Bhoolokarkum Innu Pirannallo",
          "Unni Pirannallo",
          "",
          "Bethlehem Pulkkoottil",
          "Mary Thannude Suthanayi",
          "Unni Pirannallo ....... Yeshu Pirannallo (2)",
          "",
          "Happy Christmas... Happy Christmas... Happy Christmas...",
          "",
          "( Aanadam Aanadam ....... )",
          "",
          "Kizhakkinnu Shastrimaar",
          "Thaaraththinte Gathi Nokki",
          "Vannu Gamichallo Kaazhchakal Vachchallo (2)",
          "",
          "Happy Christmas... Happy Christmas... Happy Christmas...",
          "",
          "(Aandam Aandam ....... )"
        ]
      },
      {
        "slug": "aattidayarkoru",
        "title": "Aattidayarkoru Modamudichavar Ezunnuettu",
        "listLabel": "Aattidayarkoru Modamudichavar Ezunnu",
        "order": 13,
        "lines": [
          "Aattidayarkoru Modamudichavar Ezunnuettu",
          "Palayugam Nokki",
          "Kando Raajakumaaran, Mary Kaannmaan Yaathraayi -(2)",
          "",
          "Jyothissu Vaasikal Ottukkurichu Paranjathupole",
          "Avar Chonnapole",
          "Sheeghram Poornamodam Eerivannu Yaathraayi -(2)",
          "",
          "Avar kandathu Vaikkuvaththaare",
          "Nokki Nadannathu Doore",
          "Kandavar Komala Baalane",
          "Besh - Besh - Besh",
          "",
          "(Aattidayarkoru Modamudichavar ...)",
          "",
          "Aththalakkatti Sukhaththae Muttum Paadaththinkal",
          "Ponnnu Paadaththinkal",
          "Avar Ponnnu Mooru Kunthirikkam Kaazhchavachu -(2)",
          "",
          "Avar kandathu Vaikkuvaththaare",
          "Nokki Nadannathu Doore",
          "Kandavar Komala Baalane",
          "Besh - Besh - Besh",
          "",
          "(Aattidayarkoru Modamudichavar ...)"
        ]
      },
      {
        "slug": "chandranumtharangalum",
        "title": "Chandranum Thaarangalum",
        "listLabel": "Chandranum Thaarangalum",
        "order": 2,
        "lines": [
          "Chandranum Thaarangalum",
          "Theliyunna Sheethala Raavil",
          "Lokathin Paalakanaayi",
          "Uyirekum Naathan Piranne",
          "",
          "Varuvin Varuvin Modamode",
          "Pullkoottil Chennonnu Kandeedaam (2)",
          "",
          "Kaikalanakki Melle Kannu Thurannu",
          "Kunji Lokathin Muthayi Theerneedunnu",
          "Maryathin Makanayi Maalokarkellaamee",
          "Snehathin Vachanangal Nalkeeduvaan (2)",
          "",
          "Bhooolokavum Ee Maalokarum",
          "onnayi Ninne Stuthicheedunnu (2)",
          "",
          "La La La La La La La La La La",
          "La La La La La La La La La La (2)",
          "Chandranum. (Chandranum Thaarangalum..)"
        ]
      },
      {
        "slug": "dhayvadhoodhanmaar",
        "title": "Rajarajaneshurajan Inneeravathil",
        "lines": [
          "Rajarajaneshurajan Inneeravathil",
          "Lokathinte Rakshakkaayi Jaatham Cheythallo",
          "Devadeva Paithaline Kanduvaṇangaan",
          "Aattidayar Koottamaayi Yaathraayaalloo",
          "",
          "Daivadoothanmar Onnu Cheythu Paadi Unnathangalil Daivamahathwam (2)",
          "",
          "Swargabhavanam Parityajichu Kaalikkoottil Vannu Pirannu",
          "Aadaminte Paapam Pookkidaanayi",
          "Daivaputhran Marthyanayallo (2)",
          "",
          "(Daivadoothanmar Onnu Cheythu Paadi ...)",
          "",
          "Agnirathathil Adhivasikkum",
          "Maalakhaamaarude Adhipan",
          "Shishuvineppol Kanyakathanthae",
          "Madhithattil Urangiyallo (2)",
          "",
          "(Daivadoothanmar Onnu Cheythu Paadi ...)",
          "",
          "Tune : Karthavin Vaaravil Namme Eduthidumpol",
          "",
          "reference https://youtu.be/uWYPMAzFhhk?si=8IRNllTNSF6MyBUd"
        ]
      },
      {
        "slug": "gabriyelinte",
        "title": "Gabriyellinte darshanasafalyamaayi",
        "listLabel": "Gabriyellinte darshanasafalyamaayi",
        "order": 21,
        "lines": [
          "Gabriyellinte darshanasafalyamaayi..",
          "Sarvalokarkkum nannmayaekum karunyamaayi",
          "Bethlaheminte maariloraaromal unni pirannallo (2)",
          "Vinnil thaarakal punchiri thooki",
          "Mannil Gloria naadangal paadi",
          "Avan pallikkacha aninjittu kannumchimmi thurannittu",
          "Kunjikkalittadikukayaayi..",
          "Ennum aaghosham unarukayaayi",
          "",
          "Hey.. dooreninnum thangathil",
          "Sammanangal kondeethi.",
          "Rajaakkalmaar onnaayi neele",
          "Vaazhthippadi.. Ye.. Hallelujah ...",
          "Ennum ninne lokathaayi",
          "Ullorellam vaazhthunne",
          "Innum ninte snehathaaley",
          "Dhanyam dhanyam vaaneedunne",
          "Raajadhiraajane ente maargadeepame",
          "En jeevadhaarayil chaithanyamaakane",
          "Ulkkoottile pulpaayayil",
          "Kanivaayi vaazhane..",
          "",
          "Pottaas pookkutti kambithiri ...",
          "Mathaappu rocket chembuthiri",
          "Gabriyellinte darshanasafalyamaayi..",
          "Sarvalokarkkum nannmayaekum karunyamaayi",
          "Bethlaheminte maariloraaromal unni pirannallo",
          "Unni pirannallo.. unni pirannallo",
          "Vinnil thaarakal punchiri thooki",
          "Mannil Gloria naadangal paadi",
          "Avan pallikkacha aninjittu kannumchimmi thurannittu",
          "Kunjikkalittadikukayaayi..",
          "Ennum aaghosham unarukayaayi"
        ]
      },
      {
        "slug": "kannum-kannum",
        "title": "Kannum Kannum Kaathirunnu",
        "lines": [
          "Kannum Kannum Kaathirunnu",
          "Manniloru Paithalinaai",
          "Kathodu Kathoram Kettirunnu",
          "Daivaputhran Pirakkumennu",
          "- Kannum Kannum Kaathirunnu",
          "",
          "Aakasha Veedhiyil Malaakka Maaravar",
          "Snehathin Nirakudamaai",
          "Thalaattu Paadi Urakkeeduvanaayi",
          "Manathaaril Ninachirunnu - 2",
          "",
          "Ethra Nalla Snehatthe",
          "Thanna Nalla Naadhane",
          "Melle Raavil Paadi Sthuthikkaam - 2",
          "",
          "- Kannum Kannum Kaathirunnu",
          "",
          "Jeevante Paathayil Kaarunya Kanavaai",
          "Karunardran Alinja Dhinam",
          "Aalolamatti Laalichiduvanaayi",
          "Krupayil Niranjirunnu - 2",
          "Ethra Nalla Snehatthe",
          "Thanna Nalla Naadhane",
          "Melle Raavil Paadi Sthuthikkaam - 2",
          "",
          "- Kannum Kannum Kaathirunnu"
        ]
      },
      {
        "slug": "kannumkannum",
        "title": "Kannum Kannum Kaathirunnu",
        "listLabel": "Kannum Kannum Kaathirunnu",
        "order": 1,
        "lines": [
          "Kannum Kannum Kaathirunnu",
          "Manniloru Paithalinayi",
          "Kaathodu Kaathoram Kettirunnu",
          "Daivaputhran Pirakkumennu (2)",
          "",
          "Aakaashaveethiyil Maalaakhamaaravar",
          "Snehaththinte Nirakudamaayi",
          "Tharaattupaadi Urakkeeduvanaayi",
          "Manaththaril Ninachirunnu (2)",
          "",
          "Ithranalla Snehaththae Thanna Nalla Naaththane",
          "Melle Raavil Paadisthuthikkaam (2)",
          "",
          "Kannum Kannum Kaathirunnu…….",
          "",
          "Jeevanthre Paathayil Kaarunyakanavaayi",
          "Karunaardran Alinja Dinam",
          "Aalolamaatti Laalichiduvaanaayi",
          "Kripayil Niranjirunnu (2)",
          "",
          "Ithranalla Snehaththae Thanna Nalla Naaththane",
          "Melle Raavil Paadisthuthikkaam (2)",
          "",
          "Kannum Kannum Kaathirunnu……."
        ]
      },
      {
        "slug": "kanyakayamma",
        "title": "Kanyakayamma Badalaheemin Pokunnueraam",
        "listLabel": "Kanyakayamma Badalaheemin",
        "order": 18,
        "lines": [
          "Kanyakayamma Badalaheemin Pokunnueraam",
          "Thuna Koode Poyoraousephum Thaanumaayi (2)",
          "Bethlehem Malancharive Pokunnueraam",
          "Amma Vidhana Sahiyaathe Pulkkooduthannil (2)",
          "",
          "Naalum Moonnum Randum Onnum Maasamaayi",
          "Appol Ponkumaaran Pulkkoodaththil Jaathanaayi (2)",
          "",
          "(Kanyakayamma Badalaheemin Pokunnueraam ...)"
        ]
      },
      {
        "slug": "munnamparasudhan-1",
        "title": "Munnampara Suthan Ambara Naayakan",
        "lines": [
          "Munnampara Suthan Ambara Naayakan",
          "Emmanuveloru Naariyaakum Marythan",
          "Nandhananomana Baalakan Aayaval",
          "Madiyilirunnanathum Vismayam",
          "",
          "Mannil Naranude Vadivu Dharichu",
          "Pirannoru Suravaranude Jananathe",
          "Ambara Suraganam Idayorodariyich-",
          "chathi Modichaarathum Vismayam",
          "",
          "Aattidayar Surar Cholliya Vaachakam",
          "Kettudanodiya Bethalahem Pul",
          "Koottilamarnnoru Shishuvine Vannavar",
          "Vandanam Cheithaarathum Vismayam",
          "",
          "(Munnampara Suthan Ambara Naayakan ...)"
        ]
      },
      {
        "slug": "munnamparasudhan",
        "title": "Munnam Parasuthan",
        "listLabel": "Munnam Parasuthanambara Naayakan",
        "order": 14,
        "lines": [
          "Munnam Parasuthanamabara Naayakan",
          "Immanuveloru Naariyaam Merithan",
          "Nandananomana Baalakanayaval",
          "Madiyi Irunna Naathum Vismayam",
          "",
          "Mannil Nararude Vadivu Dharichu",
          "Pirannoru Suravaranude Jananathe",
          "Ambara Suraganamidayarodariya",
          "Chchathi Modichaarathum Vismayam",
          "Aattidayar Surar Cholliya Vaachakam",
          "Kettudanoadiya Bethlehem Pul",
          "Koottilamarunnoru Shishuvine Vannavaru",
          "Vandanam Cheytha Raathum Vismayam",
          "",
          "(Munnam Parasuthanamabara Naayakan ...)"
        ]
      },
      {
        "slug": "muthe-muthe",
        "title": "Muthe Muthe Muthe Ponnomane",
        "listLabel": "Muthe Muthe Muthe Ponnomane",
        "order": 3,
        "lines": [
          "Muthe Muthe Muthe Ponnomane",
          "Ninne Kaanan Kothichoru Naalil",
          "Manju Peyyunna Thaazvarayil",
          "Oru Jeevaninte Kaliyattamaayi",
          "",
          "Muthe Muthe.. Chakkara Muthe...",
          "Muthe Muthe.. Chakkara Muthe...",
          "",
          "Muthe Muthe Muthe Ponnomane",
          "Ninne Kaanan Kothichoru Naalil",
          "Manju Peyyunna Thaazvarayil",
          "Oru Jeevaninte Kaliyattamaayi",
          "",
          "Doore Doore Ninnum Thaarakal Paadi",
          "Raajaadhi Raajaavivan",
          "Snehathin Thoolika Mannil Chalippicha",
          "Devaadhideivamivan (2)",
          "Mannil Snehathin Ennum Vaarichorinjidum",
          "Swargeeya Naayakanaayi (2)",
          "",
          "Muthe Muthe.. Chakkara Muthe...",
          "Muthe Muthe.. Chakkara Muthe...",
          "",
          "(Muthe Muthe Muthe ...)"
        ]
      },
      {
        "slug": "naamchernupadidam",
        "title": "Naam Chernnu Paadidam",
        "listLabel": "Naam Chernnu Paadidam",
        "order": 6,
        "lines": [
          "Naam Chernnu Paadidam",
          "Naam Aarthu Paadidam",
          "Bethlehem Kaali Pulkoottil",
          "",
          "Paapikale Raksha Cheyyuvaan",
          "Yeshu Raajan Jathanaayallo (2)",
          "",
          "Doothanmar Halleluya Paadunnu",
          "Aattidayar Gaanam Kettunarunnu (2)",
          "",
          "Ponnu Mooru Kunthirikkavumaayi",
          "Vidwaanmaar Yathraayaayallo (2)",
          "",
          "(Naam Chernnu Paadidam ....)",
          "",
          "Thaarakam Vaanil Angudichallo",
          "Vinnil Shobha Raavunarnnarinjalallo (2)",
          "",
          "Ponnu Mooru Kunthirikkavumaayi",
          "Vidwaanmaar Yathraayaayallo (2)",
          "",
          "(Naam Chernnu Paadidam ....)"
        ]
      },
      {
        "slug": "orutharam",
        "title": "Thaaramang Vaanil Uyarnnu Kandu",
        "listLabel": "Oru Thaaramang Vaanil (Jin Jilu)",
        "order": 15,
        "lines": [
          "Oru Thaaramang Vaanil Uyarnnu Kandu",
          "O Raajante Jananathin Mahimakandu (2)",
          "",
          "Jin Jilu Jilu Jilu Piranna Mannil",
          "O Jin Jilu Jilu Jilu",
          "Jin Jilu Jilu Jilu Piranna Mannil",
          "",
          "Paaravakalanavadhy Kalla Kalla Gaanangal",
          "Mannavan Jananathin Kavithapaadi",
          "O Kavithapaadi (2)",
          "",
          "(Jin Jilu Jilu Jilu Piranna Mannil ...)",
          "",
          "Shaastrikalanavadhy Ponnu Moorthu Kunthirikkam",
          "Shishuvinte Kaalkalaayi Kaazhchavachu",
          "O Kaazhchavachu (2)",
          "",
          "(Jin Jilu Jilu Jilu Piranna Mannil ...)"
        ]
      },
      {
        "slug": "paadathepoyaalpora",
        "title": "Paadathe Poyaal Poraa",
        "listLabel": "Paadathe Poyaala Poraa",
        "order": 9,
        "lines": [
          "Paadathe Poyaal Poraa",
          "Paattoru Paadi Aadenam (2)",
          "",
          "Melaakkaar Melaam Thudanghi",
          "Halleluya Paadennam (2)",
          "",
          "Pulkoottil Pirannathallo",
          "Aaraaro Pirannathaaro",
          "Thirumoziyil Kali Parayum",
          "Meri Than Sunuvaane (2)",
          "",
          "Janana Sudinam Innaanallo",
          "Janmadinam Aarthughoseekkaam (2)",
          "Ponninte Nirakudamalle",
          "Pinne Enthinee Pattusheelaakal (2)",
          "Jananathaal Viduthal Veenam",
          "Puthiya Paattu Paadenam (2)",
          "",
          "(Pulkoottil Pirannathallo ...)"
        ]
      },
      {
        "slug": "pallimedayil",
        "title": "Palli Medayil Melle Manikal Muzhungi",
        "listLabel": "Palli Medayil Melle",
        "order": 4,
        "lines": [
          "Palli Medayil Melle Manikal Muzhungi",
          "Maalokar Aandamodu Unarnnithaa",
          "Nakshathram Thookiyum Thoranangale Chaarthiyum",
          "Poothirikal Kathichum Poomarangal Orukkiyum",
          "Naathane Varaveetidum (2)",
          "",
          "Angakale Aakaashathil",
          "Navathaaram Melle Udichu",
          "Thaarangal Minni Thelinju",
          "Stuthigeetham Paadi Ninnu (2)",
          "",
          "Manju Peyyum Thaazvarayil Devadaaru Poothathum",
          "Maryathin Makananallo Ee Snehathin Thiriyalanallo",
          "La Laalalalala Laalalalala Laalalalala La La La (2)",
          "",
          "(Palli Medayil...)"
        ]
      },
      {
        "slug": "paloolithookia",
        "title": "Paaloli Thookiya Paathiraa Neraththu",
        "listLabel": "Paaloli Thookiya Paathiraa Neraththu",
        "order": 5,
        "lines": [
          "Paaloli Thookiya Paathiraa Neraththu",
          "Paarithil Pirannone",
          "",
          "Paapangal Pokkane",
          "Shaapangal Theerkane",
          "Dharaniyin Adhipathiye (2)",
          "",
          "Kusumangal Vidaratte Parimalam Parakatte",
          "Shoonyapradeshangal Aarthidatte (2)",
          "Devakumaara Raajakumaara Daavidin Vamshajane",
          "Kalangangal Kazhukidane (2)",
          "",
          "(Paaloli Thookiya...)",
          "",
          "Mayilukal Aadatte Kuyilukal Paadatte",
          "Vayalugal Karivala Kilukkidatte (2)",
          "Devakumaara Raajakumaara Daavidin Vamshajane",
          "Kalangangal Kazhukidane (2)",
          "",
          "(Paaloli Thookiya...)"
        ]
      },
      {
        "slug": "patttuvirichamethakal",
        "title": "Pattuviricha Methakalilla",
        "listLabel": "Pattuviricha Methakallilla",
        "order": 11,
        "lines": [
          "Pattuviricha Methakalilla",
          "Mandhiramilla Shayippaanayi",
          "Verumoru Kaali Pulkkoodathil",
          "Rakshakaneshu Pirannallo",
          "En Rakshakaneshu Pirannallo",
          "",
          "Kaalum Melum Novunnille",
          "Kambili Illae Puthaykkaanayi (2)",
          "",
          "Sankadamundhithu Kaanaambolum",
          "Thangakudame Ponnunni (2)",
          "",
          "Ponnunni Ninakkenthé",
          "Maanathu Vasippaanayi",
          "Maalore Thedi Nee",
          "Thaazhothu Vannallo (2)",
          "",
          "Pattuviricha Methakalilla",
          "Mandhiramilla Shayippaanayi",
          "Verumoru Kaali Pulkkoodathilayi",
          "En Rakshakaneshu Pirannallo (2)"
        ]
      },
      {
        "slug": "poothiri",
        "title": "Poothiri Mattappoo Minni Thilanjunna",
        "listLabel": "Poothiri Mathaappoo",
        "order": 17,
        "lines": [
          "Poothiri Mattappoo Minni Thilanjunna",
          "Mangala Mani Muzhanghi",
          "Varna Kadalaasu Nakshatra Deepangal",
          "ChandathiloruNgiyaallo (2)",
          "",
          "Pravachakannmaarum Munimaarum Ponnavadharam Pravachichallo(2)",
          "Eelokam Kaanaatha Ponsudheenam",
          "En Mashiha Avadhichu (2)",
          "",
          "(Poothiri Mattappoo Minni Thilanjunna ...)"
        ]
      },
      {
        "slug": "poyidaam-koottare",
        "title": "Poyidam Koottare",
        "listLabel": "Poyidam Koottare",
        "order": 7,
        "lines": [
          "Poyidam Koottare Swargaloka Naathante",
          "Jananaththe Lokamengum Ghoshicheedam (2)",
          "Thapputhala Melamode Ottu Chernnu Paadidam",
          "Swarganaathan Bhoovil Vanna Sudinam",
          "Paattu Paadi Ghoshicheedam – Inn –",
          "Aarthupaadi Ghoshicheedam (2)",
          "",
          "Raajaadhiraajaavaam Sreeyeshunaathante",
          "Thripadam Kumbiddeedam (2)",
          "Aamodaraayinnu Aanandageethikalal",
          "Saamodam Vaazhtippaadam (2)",
          "(Poyidam Koottare...)",
          "",
          "Ajapaalakar Ellam Aahlaadathaalinnu",
          "Naathane Stuthicheedunnu (2)",
          "Shaasthrimaar Moovarum Kaazhchakal Arppichu",
          "Raajane Vandikkunnu (2)",
          "(Poyidam Koottare...)"
        ]
      },
      {
        "slug": "pulkudilil",
        "title": "Pullkutilil Kalthottiyil",
        "listLabel": "Pullkutilil Kalthottiyil",
        "order": 8,
        "lines": [
          "Pullkutilil Kalthottiyil",
          "Maryathin Pon Makanayi",
          "Pandoru Naal Daivasuthan",
          "Pirannathin Orma Dinam (2)",
          "",
          "Poru Mannile Idayanmare",
          "Paadoo Vinnile Maalaakhakale (2)",
          "Paadum Thamburuvum",
          "Kinnaravum Thaalavumaayi (2)",
          "",
          "(Pullkuttilil Kalthottiyil ...)",
          "",
          "Melshyarum Kasparum",
          "Belthasarum Vaazhtthum",
          "Rakshakaril Rakshakanaam Mishiha Piranna Dinam (2)",
          "",
          "Poru Mannile Idayanmare",
          "Paadoo Vinnile Maalaakhakale (2)",
          "Paadum Thamburuvum",
          "Kinnaravum Thaalavumaayi (2)",
          "",
          "(Pullkuttilil Kalthottiyil ...)",
          "",
          "Bhoomiyil Daivamakkal",
          "Neadum Samaadhaanam",
          "Unnathiyil Atyunnathiyil",
          "Daivathinnu Mahathwam (2)",
          "",
          "Poru Mannile Idayanmare",
          "Paadoo Vinnile Maalaakhakale (2)",
          "Paadum Thamburuvum",
          "Kinnaravum Thaalavumaayi (2)",
          "",
          "(Pullkuttilil Kalthottiyil ...)"
        ]
      },
      {
        "slug": "sam-sam-sambramay",
        "title": "Sam Sam Sampramaayi",
        "listLabel": "Sam Sam Sampramaayi",
        "order": 10,
        "lines": [
          "Sam Sam Sampramaayi Sangamikum Thingalayi (2)",
          "Nasaraayaṁ Pashukkootil Pirannone (2)",
          "Pirannone Pashukkootil Thaanē (2)",
          "Thaara Ka Kodiyayi Pirannone (2) (Sam Sam)",
          "",
          "Thatha Mayilukal Kuyilukal Aakaashathil (2)",
          "Orthaadi Paadidunnu Jayamode",
          "Avar Orthaadi Paadidunnu Jayamode",
          "",
          "Puththanaay - Thatthakal Stuthiye (2)",
          "Poorthiyaayi Kettathum Athishayame (2)",
          "",
          "(Sam Sam Sampramaayi ...)",
          "",
          "Aattidayar Koottavum Thaanē (2)",
          "Kaattiya Velichavum Kandudanunarnnu (2) (Sam Sam)",
          "",
          "(Sam Sam Sampramaayi ...)"
        ]
      },
      {
        "slug": "thaarakamvannidhiche",
        "title": "Thaarakam vannudiche",
        "listLabel": "Thaarakam vannudiche",
        "order": 20,
        "lines": [
          "Thaa thinanthaka theythaaro",
          "Thakathinanthaka theythaaro",
          "Thaa thinanthaka thakathinanthaka",
          "Thakathinanthaka theythaaro (2)",
          "",
          "Thaarakam vannudiche",
          "Annu Bethleham pulkkudilil",
          "Vidwanmaar moovarum kaazhchakalumaayi vanna",
          "Naathane kaananaethi (2)",
          "",
          "(Thaa thinanthaka theythaaro ... )",
          "",
          "Maalakha vrindaminni",
          "Thaarattu paadidumpol",
          "Aahlaadathode naam kaikottippaaduka",
          "Rakshakan jaathanayi (2)",
          "",
          "(Thaa thinanthaka theythaaro ... )",
          "",
          "Manju peyyunnee raavil",
          "Thaaram punchiri thookum raavil",
          "Aamodathode naam vaazhthippaadiduka",
          "Rakshakan jaathanayi (2)",
          "",
          "(Thaa thinanthaka theythaaro ... )",
          "",
          "s"
        ]
      },
      {
        "slug": "yahoodhiyayille",
        "title": "Yahoodhiyaile Oru Graamaththil",
        "listLabel": "Yahoodhiyaayille Oru Graamaththil",
        "order": 19,
        "lines": [
          "Yahoodhiyaile Oru Graamaththil",
          "Oru Dhanumaasaththin Kulirum Raavil",
          "Raapaarthirunnoru Japaalakar",
          "Devanadam Kettu Aamodaraayi",
          "Varnnarajikal Vidirum Vaanil",
          "Vellimeghangal Ozhukum Raavil",
          "Taarakaa Rajakumaariyodothunnu",
          "Thingal Kalapaadi Glory..",
          "Annu Thingal Kalapaadi Glory..",
          "",
          "Taarakam Thanne Nookki Aattidayar Nadannu (2)",
          "Thejassu Munnilkkandu Avr",
          "Bethlehem Thannil Vannu (2)",
          "Raajaadhiraajaante Ponthirumeeni (2)",
          "Avr Kaalithozhuththilkkandu",
          "",
          "Varnnarajikal Vidirum Vaanil",
          "Vellimeghangal Ozhukum Raavil",
          "Taarakaa Rajakumaariyodothunnu",
          "Thingal Kalapaadi Glory..",
          "Annu Thingal Kalapaadi Glory..",
          "",
          "Mannavar Moovarum Daaveedhin Suthane ..(2)",
          "Kandu Vanangiduvan Avr Kaazhchayumaayi Vannu (2)",
          "Devaadidevante Thirusannidhiyil",
          "Avr Kaazhchakal Vachu Vanangi (2)",
          "",
          "Varnnarajikal Vidirum Vaanil",
          "Vellimeghangal Ozhukum Raavil",
          "Taarakaa Rajakumaariyodothunnu",
          "Thingal Kalapaadi Glory..",
          "Annu Thingal Kalapaadi Glory..",
          "",
          "(Yahoodhiyaile Oru Graamaththil ...)"
        ]
      }
    ]
  },
  "ml": {
    "$schema": "../song-language.schema.json",
    "language": "ml",
    "htmlLang": "ml",
    "indexFile": "index.html",
    "churchName": "തുരുത്തിക്കാട് മാർത്തോമ്മാ ഇടവക",
    "collectionTitle": "കരോൾ റൗണ്ട്സ് ഗാനങ്ങൾ",
    "description": "തുരുത്തിക്കാട് മാർത്തോമ്മാ ഇടവക കരോൾ റൗണ്ട്സ് ഗാനങ്ങൾ",
    "fontClass": "arima-Malayalam",
    "songs": [
      {
        "slug": "aadi-aadi-paduvaan",
        "title": "ആടി ആടി പാടുവാനായി",
        "listLabel": "ആടി ആടി പാടുവാനായി",
        "order": 16,
        "lines": [
          "ആടി ആടി പാടുവാനായി",
          "നാട്ടിൽ കൊണ്ടാടുവാൻ",
          "അ. അ. ആ...",
          "ആടി ആടി പാടുവാനായി",
          "നാട്ടിൽ കൊണ്ടാടുവാൻ",
          "വീടുതോറും നമ്മളെല്ലാം തുള്ളിയാടി പോകണം (2)",
          "",
          "വന്നല്ലോ ശാന്തി പോയല്ലോ ശണ്ഠകൾ (2)",
          "ഇല്ലല്ലോ മത്സരം നാം ഒന്നായി പാടുവാൻ",
          "നാം ഒന്നായി പാടുവാൻ",
          "",
          "(ആടി ആടി പാടുവാനായി...)",
          "",
          "രാജാധി രാജൻ ബേത്ലഹേം ഗോശാലെ (2)",
          "ഭൂജാതം ചെയ്തതാം വാർത്തയെ പാടുവാൻ",
          "വാർത്തയെ പാടുവാൻ",
          "",
          "(ആടി ആടി പാടുവാനായി...)"
        ]
      },
      {
        "slug": "aanandham-aanandham",
        "title": "ആനന്ദം ആനന്ദം ആഹാ മാനവരെ",
        "listLabel": "ആനന്ദം ആനന്ദം ആഹാ മാനവരെ",
        "order": 12,
        "lines": [
          "ആനന്ദം ആനന്ദം ആഹാ മാനവരെ",
          "സ്വര്‍ലോകരെല്ലാം ഭൂലോകര്‍ക്കും ഇന്ന് പിറന്നല്ലോ",
          "ഉണ്ണി പിറന്നല്ലോ",
          "",
          "ബെത്ലഹേം പുല്‍ക്കൂട്ടില്‍",
          "മേരി തന്നുടെ സുതനായി",
          "ഉണ്ണി പിറന്നല്ലോ ....... യേശു പിറന്നല്ലോ (2)",
          "",
          "ഹാപ്പി ക്രിസ്മസ്‌ ...  ഹാപ്പി ക്രിസ്മസ്‌ ...  ഹാപ്പി ക്രിസ്മസ്‌ ...",
          "",
          "( ആനന്ദം ആനന്ദം ....... )",
          "",
          "കിഴക്ക്‌ നിന്ന്‌ ശാസ്ത്രിമാർ",
          "താരത്തിന്റെ ഗതി നോക്കി",
          "വന്നു ഗമിച്ചല്ലോ കാഴ്ചകള്‍ വച്ചല്ലോ (2)",
          "",
          "ഹാപ്പി ക്രിസ്മസ്‌ ...  ഹാപ്പി ക്രിസ്മസ്‌ ...  ഹാപ്പി ക്രിസ്മസ്‌ ...",
          "",
          "(ആനന്ദം ആനന്ദം .......  )"
        ]
      },
      {
        "slug": "aattidayarkoru",
        "title": "ആട്ടിടയര്‍ക്കൊരു മോദമുദിച്ചവര്‍ എഴുന്നേറ്റ്‌",
        "listLabel": "ആട്ടിടയര്‍ക്കൊരു മോദമുദിച്ചവര്‍",
        "order": 13,
        "lines": [
          "ആട്ടിടയര്‍ക്കൊരു മോദമുദിച്ചവര്‍ എഴുന്നേറ്റ്‌",
          "പലയുഗം നോക്കി",
          "കണ്ടോ രാജകുമാരന്‍, മേരി കാണ്മാന്‍ യാത്രയായി -(2)",
          "",
          "ജ്യോതിസ്സു വാസികള്‍ ഒത്തുകുറിച്ചു പറഞ്ഞതുപോലെ",
          "അവര്‍ ചൊന്നപോലെ",
          "ശീഘ്രം പൂര്‍ണ്ണമോദം ഏറിവന്നു യാത്രയായി",
          "",
          "അവർ കണ്ടത് വയ്ക്കുവതാരെ",
          "നോക്കി നടന്നത്‌ ദൂരെ",
          "കണ്ടവര്‍ കോമള ബാലനെ",
          "ഭേഷ്‌- ഭേഷ്‌ - ഭേഷ്‌",
          "",
          "(ആട്ടിടയര്‍ക്കൊരു മോദമുദിച്ചവര്‍ ... )",
          "",
          "അത്തലകറ്റി സുഖത്തെ മുറ്റും പാദത്തിങ്കൽ",
          "പൊന്നു പാദത്തിങ്കല്‍",
          "അവര്‍ പൊന്നു  മൂര്‌ കുന്തിരിക്കം കാഴ്ചവച്ചു",
          "",
          "അവർ കണ്ടത് വയ്ക്കുവതാരെ",
          "നോക്കി നടന്നത്‌ ദൂരെ",
          "കണ്ടവര്‍ കോമള ബാലനെ",
          "ഭേഷ്‌- ഭേഷ്‌ - ഭേഷ്‌",
          "",
          "(ആട്ടിടയര്‍ക്കൊരു മോദമുദിച്ചവര്‍ ... )"
        ]
      },
      {
        "slug": "chandranumtharangalum",
        "title": "ചന്ദ്രനും താരങ്ങളും",
        "listLabel": "ചന്ദ്രനും താരങ്ങളും",
        "order": 2,
        "lines": [
          "ചന്ദ്രനും താരങ്ങളും",
          "തെളിയുന്ന ശീതള രാവിൽ",
          "ലോകത്തിൻ പാലകനായി",
          "ഉയിരേകും നാഥൻ പിറന്നേ",
          "",
          "വരുവിൻ വരുവിൻ മോദമോടെ",
          "പുൽക്കൂട്ടിൽ ചെന്നൊന്നു കണ്ടീടാം (2)",
          "",
          "കൈകളനക്കി മെല്ലെ കണ്ണു തുറന്നു",
          "കുഞ്ഞി ലോകത്തിൻ മുത്തായി തീർന്നീടുന്നു",
          "മറിയത്തിൻ മകനായി മാലോകർക്കെല്ലാമീ",
          "സ്നേഹത്തിൻ വചനങ്ങൾ നൽകീടുവാൻ (2)",
          "",
          "ഭൂലോകവും ഈ മാലോകരും",
          "ഒന്നായി നിന്നെ സ്തുതിച്ചീടുന്നു (2)",
          "",
          "ലാ ലാ ലാ ലാ ല ല ലാ ലാ ലാ ലാ",
          "ലാ ലാ ലാ ലാ ല ല ലാ ലാ ലാ ലാ (2)",
          "ചന്ദ്രനും. (ചന്ദ്രനും താരങ്ങളും..)"
        ]
      },
      {
        "slug": "dhayvadhoodhanmaar",
        "title": "രാജരാജനേശുരാജൻ ഇന്നീരാവതിൽ",
        "lines": [
          "രാജരാജനേശുരാജൻ ഇന്നീരാവതിൽ",
          "ലോകത്തിന്റെ രക്ഷക്കായി ജാതം ചെയ്തല്ലോ",
          "ദേവദേവ പൈതലിനെ കണ്ടുവണങ്ങാൻ",
          "ആട്ടിടയർ കൂട്ടമായി യാത്രയായല്ലോ",
          "",
          "ദൈവദൂതന്മാർ ഒന്നിച്ചു പാടി ഉന്നതങ്ങളിൽ ദൈവമഹത്വം (2)",
          "",
          "സ്വർഗ്ഗഭവനം പരിത്യജിച്ച് കാലിക്കൂട്ടിൽ വന്നു പിറന്നു",
          "ആദാമിന്റെ പാപം പോക്കിടാനായി",
          "ദൈവപുത്രൻ മർത്യനായല്ലോ(2)",
          "",
          "(ദൈവദൂതന്മാർ ഒന്നിച്ചു പാടി ...)",
          "",
          "അഗ്നിരഥത്തിൽ അധിവസിക്കും",
          "മാലാഖമാരുടെ അധിപൻ",
          "ശിശുവിനെപ്പോൽ കന്യകതന്റെ",
          "മടിത്തട്ടിൽ ഉറങ്ങിയല്ലോ (2)",
          "",
          "(ദൈവദൂതന്മാർ ഒന്നിച്ചു പാടി ...)",
          "",
          "Tune : കര്‍ത്താവിന്‍ വരവില്‍ നമ്മെ എടുത്തിടുമ്പോള്‍",
          "",
          "reference https://youtu.be/uWYPMAzFhhk?si=8IRNllTNSF6MyBUd"
        ]
      },
      {
        "slug": "gabriyelinte",
        "title": "ഗബ്രിയേലിന്റെ ദര്‍ശനസാഫല്യമായ്..",
        "listLabel": "ഗബ്രിയേലിന്റെ ദര്‍ശനസാഫല്യമായ്",
        "order": 21,
        "lines": [
          "ഗബ്രിയേലിന്റെ ദര്‍ശനസാഫല്യമായ്..",
          "സർവ്വലോകർക്കും നന്മയേകും കാരുണ്യമായ്",
          "ബെത്‌ലഹേമിന്റെ മാറിലൊരാരോമൽ ഉണ്ണി പിറന്നല്ലോ (2)",
          "വിണ്ണിൽ താരകൾ പുഞ്ചിരി തൂകി",
          "മണ്ണിൽ ഗ്ലോറിയ നാദങ്ങൾ പാടി",
          "അവൻ പള്ളിക്കച്ച അണിഞ്ഞിട്ട് കണ്ണുംചിമ്മി തുറന്നിട്ട്",
          "കുഞ്ഞിക്കാലിട്ടടിക്കുകയായ് ..",
          "എന്നും ആഘോഷം ഉണരുകയായ്",
          "",
          "ഹേ.. ദൂരെനിന്നും തങ്കത്തിൽ",
          "സമ്മാനങ്ങൾ കൊണ്ടെത്തി.",
          "രാജാക്കന്മാർ ഒന്നായ് നീളെ",
          "വാഴ്ത്തിപ്പാടി.. യേ.. ഹല്ലേലൂയാ ...",
          "എന്നും നിന്നെ ലോകത്തായ്‌",
          "ഉള്ളോരെല്ലാം വാഴ്ത്തുന്നേ",
          "ഇന്നും നിന്റെ സ്നേഹത്താലേ",
          "ധന്യം ധന്യം വാണീടുന്നെ",
          "രാജാധിരാജനേ എന്റെ മാർഗ്ഗദീപമേ",
          "എൻ ജീവധാരയിൽ ചൈതന്യമാകണേ",
          "ഉൾക്കൂട്ടിലെ പുൽപ്പായയിൽ",
          "കനിവായ് വാഴണേ ..",
          "",
          "പൊട്ടാസ് പൂക്കുറ്റി കമ്പിത്തിരി ...",
          "മത്താപ്പ് റോക്കറ്റ് ചെമ്പൂത്തിരി",
          "ഗബ്രിയേലിന്റെ ദര്‍ശനസാഫല്യമായ്..",
          "സർവ്വലോകർക്കും നന്മയേകും കാരുണ്യമായ്",
          "ബെത്‌ലഹേമിന്റെ മാറിലൊരാരോമൽ ഉണ്ണി പിറന്നല്ലോ",
          "ഉണ്ണി പിറന്നല്ലോ.. ഉണ്ണി പിറന്നല്ലോ",
          "വിണ്ണിൽ താരകൾ പുഞ്ചിരി തൂകി",
          "മണ്ണിൽ ഗ്ലോറിയ നാദങ്ങൾ പാടി",
          "അവൻ പള്ളിക്കച്ച അണിഞ്ഞിട്ട് കണ്ണുംചിമ്മി തുറന്നിട്ട്",
          "കുഞ്ഞിക്കാലിട്ടടിക്കുകയായ് ..",
          "എന്നും ആഘോഷം ഉണരുകയായ്"
        ]
      },
      {
        "slug": "kannumkannum",
        "title": "കണ്ണും കണ്ണും കാത്തിരുന്നു",
        "listLabel": "കണ്ണും കണ്ണും കാത്തിരുന്നു",
        "order": 1,
        "lines": [
          "കണ്ണും കണ്ണും കാത്തിരുന്നു",
          "മന്നിലൊരു പൈതലിനായി",
          "കാതോടു കാതോരം കേട്ടിരുന്നു",
          "ദൈവപുത്രൻ പിറക്കുമെന്ന് (2)",
          "",
          "ആകാശവീഥിയിൽ മാലാഖാമാരവർ",
          "സ്നേഹത്തിൻ നിറകുടമായ്",
          "തരാട്ടുപാടി ഉറക്കീടുവനായ്",
          "മനതാരിൽ നിനച്ചിരുന്നു (2)",
          "",
          "ഇത്രനല്ല സ്നേഹത്തെ തന്ന നല്ല നാഥനെ",
          "മെല്ലെ രാവിൽ പാടിസ്തുതിക്കാം (2)",
          "",
          "കണ്ണും കണ്ണും കാത്തിരുന്നു…….",
          "",
          "ജീവന്റെ പാതയിൽ കാരുണ്യകനവായ്",
          "കരുണാർദ്രൻ അലിഞ്ഞ ദിനം",
          "ആലോലമാട്ടി ലാളിച്ചിടുവാനായ്",
          "കൃപയിൽ നിറഞ്ഞിരുന്നു (2)",
          "",
          "ഇത്രനല്ല സ്നേഹത്തെ തന്ന നല്ല നാഥനെ",
          "മെല്ലെ രാവിൽ പാടിസ്തുതിക്കാം (2)",
          "",
          "കണ്ണും കണ്ണും കാത്തിരുന്നു……."
        ]
      },
      {
        "slug": "kanyakayamma",
        "title": "കന്യകയമ്മ ബേദ്ലഹെമിന് പോകുന്നേരം",
        "listLabel": "കന്യകയമ്മ ബദ്ലഹേമിന്",
        "order": 18,
        "lines": [
          "കന്യകയമ്മ ബേദ്ലഹെമിന് പോകുന്നേരം",
          "തുണ കൂടെ പോയോരൗസേഫും താനുമായി (2)",
          "ബേദ്ലഹേം മലഞ്ചരിവെ പോകുന്നേരം",
          "അമ്മ വേദന സഹിയാതെ പുൽക്കൂടുതന്നിൽ (2)",
          "",
          "നാലും മൂണും രണ്ടും ഒന്നും മാസമായി",
          "അപ്പോൾ പോൻകുമാരൻ പുൽകൂടത്തിൽ ജാതനായി (2)",
          "",
          "(കന്യകയമ്മ ബദലാഹീമിന് പോകുന്നേരം ... )"
        ]
      },
      {
        "slug": "munnamparasudhan",
        "title": "മുന്നം പരസുതനംബര നായകൻ",
        "listLabel": "മുന്നം പരസുതനംബര നായകൻ",
        "order": 14,
        "lines": [
          "മുന്നം പരസുതനംബര നായകൻ",
          "ഇമ്മാനുവേ ലൊരു നാരിയാം മേരിതൻ",
          "നന്ദനനോമന ബാലകനായവൾ",
          "മടിയി ലിരുന്നാ നാതും വിസ്മയം",
          "",
          "മന്നിൽ നരരുടെ വടിവു ധരിച്ചു",
          "പിറന്നൊരു സുരവരനുടെ ജനനത്തെ",
          "അംബര സുരഗണമിടയരോടരിയി",
          "ച്ചതി മോടിച്ചാരാതും വിസ്മയം",
          "",
          "ആട്ടിടയർ സുരർ ചൊല്ലിയ വാചകം",
          "കേട്ടുടനോടിയ ബെതലഹേം പുൽ",
          "കൂട്ടിലമർന്നൊരു ശിശുവിനെ വന്നവർ",
          "വന്ദനം ചെയ്താ രാതും വിസ്മയം",
          "",
          "( മുന്നം പരസുതനംബര നായകൻ ...)"
        ]
      },
      {
        "slug": "muthe-muthe",
        "title": "മുത്തേ മുത്തേ മുത്തേ പോന്നോമനേ",
        "listLabel": "മുത്തേ മുത്തേ മുത്തേ പോന്നോമനേ",
        "order": 3,
        "lines": [
          "മുത്തേ മുത്തേ മുത്തേ പോന്നോമനേ",
          "നിന്നെ കാണാൻ കൊതിച്ചൊരുനാളിൽ",
          "മഞ്ഞുപെയ്യുന്ന താഴ്‌വരയിൽ",
          "ഒരു ജീവന്റെ കളിയാട്ടമായി",
          "",
          "മുത്തേ മുത്തേ.. ചക്കരമുത്തെ....",
          "മുത്തേ മുത്തേ.. ചക്കരമുത്തെ....",
          "",
          "മുത്തേ മുത്തേ മുത്തേ പോന്നോമനേ",
          "നിന്നെ കാണാൻ കൊതിച്ചൊരുനാളിൽ",
          "മഞ്ഞുപെയ്യുന്ന താഴ്‌വരയിൽ",
          "ഒരു ജീവന്റെ കളിയാട്ടമായി",
          "",
          "ദൂരെ ദൂരെ നിന്നും താരകങ്ങൾ പാടി",
          "രാജാധി രാജാവിവൻ",
          "സ്നേഹത്തിൻ തൂലിക മണ്ണിൽ ചലിപ്പിച്ച",
          "ദേവാധിദൈവമിവൻ (2)",
          "മണ്ണിൽ സ്നേഹം എന്നും വാരിചൊരിഞ്ഞിടും സ്വർഗീയ നായകനായി (2)",
          "",
          "മുത്തേ മുത്തേ.. ചക്കരമുത്തെ....",
          "മുത്തേ മുത്തേ.. ചക്കരമുത്തെ....",
          "",
          "(മുത്തേ മുത്തേ മുത്തേ ...)"
        ]
      },
      {
        "slug": "naamchernupadidam",
        "title": "നാം ചേർന്നു പാടിടാം",
        "listLabel": "നാം ചേർന്നു പാടിടം",
        "order": 6,
        "lines": [
          "നാം ചേർന്നു പാടിടാം",
          "നാം ആർത്തു പാടിടാം",
          "ബേദ്ലഹേം കാലി പുൽകൂട്ടിൽ",
          "",
          "പാപികളെ രക്ഷ ചെയ്യുവാൻ",
          "യേശു രാജൻ ജാതനായല്ലോ (2)",
          "",
          "ദൂതന്മാർ ഹല്ലെല്ലൂയ്യ പാടുന്നു",
          "ആട്ടിടയർ ഗാനം കേട്ടുണരുന്നു (2)",
          "",
          "പൊന്നു മൂരു കുന്തിരിക്കവുമായ്",
          "വിദ്വാന്മാർ യാത്രയായല്ലോ.  (2)",
          "",
          "( നാം ചേർന്നു പാടിടം .... )",
          "",
          "താരകം വാനിലങ്ങുദിച്ചല്ലോ",
          "വിണ്ണിൽ ശോഭ രാവുണർന്നറിഞ്ഞല്ലോ (2)",
          "",
          "പൊന്നു മൂരു കുന്തിരിക്കവുമായ്",
          "വിദ്വാന്മാർ യാത്രയായല്ലോ.   (2)",
          "( നാം ചേർന്നു പാടിടം .... )"
        ]
      },
      {
        "slug": "orutharam",
        "title": "ഒരു താരമങ്ങ് വാനിൽ ഉയർന്നു കണ്ടു",
        "listLabel": "ഒരു താരമങ്ങ് വാനിൽ (ജിൻ ജിലു)",
        "order": 15,
        "lines": [
          "ഒരു താരമങ്ങ് വാനിൽ ഉയർന്നു കണ്ടു",
          "ഓ രാജന്റെ ജനനത്തിൻ മഹിമകണ്ടു (2)",
          "",
          "ജിൻ ജിലു ജിലു ജിലു പിറന്ന മണ്ണിൽ",
          "ഓ ജിൻ ജിലു ജിലു ജിലു",
          "ജിൻ ജിലു ജിലു ജിലു പിറന്ന മണ്ണിൽ",
          "",
          "പാറവകളനവധി കള കള ഗാനങ്ങൾ",
          "മണ്ണവൻ ജനനത്തിൻ കവിതപാടി",
          "ഓ കവിതപാടി (2)",
          "",
          "(ജിൻ ജിലു ജിലു ജിലു പിറന്ന മണ്ണിൽ …)",
          "",
          "ശാസ്ത്രീകളങ്ങനവധി പൊന്നു മൂരു കുന്തിരിക്കം",
          "ശിശുവിൻറെ കാൽക്കലായി കാഴ്ചവച്ചു",
          "ഓ കാഴ്ചവച്ചു (2)",
          "",
          "(ജിൻ ജിലു ജിലു ജിലു പിറന്ന മണ്ണിൽ …)"
        ]
      },
      {
        "slug": "paadathepoyaalpora",
        "title": "പാടാതെ പോയാൽ പോരാ",
        "listLabel": "പാടാതെ പോയാൽ പോരാ",
        "order": 9,
        "lines": [
          "പാടാതെ പോയാൽ പോരാ",
          "പാട്ടൊന്നു പാടി ആടേണം  (2)",
          "",
          "മേളക്കാർ മേളം തുടങ്ങി",
          "ഹല്ലെലുയ്യ പാടേണം (2)",
          "",
          "പുൽക്കൂട്ടിൽ പിറന്നതല്ലോ",
          "ആരാരോ പിറന്നതാരോ",
          "തിരുമൊഴിയിൽ കളി പറയും",
          "മേരി തൻ സൂനുവാണേ (2)",
          "",
          "ജനന സുദിനം ഇന്നാണല്ലോ",
          "ജന്മദിനം ആർത്തുഘോഷിക്കാം (2)",
          "പൊന്നിന്റെ നിറകുടമല്ലേ",
          "പിന്നെന്തിനീ പട്ടുശീലകൾ (2)",
          "ജനനത്താൽ വിടുതൽ വേണം",
          "പുതിയ പാട്ട് പാടേണം (2)",
          "",
          "(പുൽക്കൂട്ടിൽ പിറന്നതല്ലോ ... )"
        ]
      },
      {
        "slug": "pallimedayil",
        "title": "പള്ളി മേടയിൽ മെല്ലെ മണികള്‍ മുഴങ്ങി",
        "listLabel": "പള്ളി മേടയിൽ മെല്ലെ",
        "order": 4,
        "lines": [
          "പള്ളി മേടയിൽ മെല്ലെ മണികള്‍ മുഴങ്ങി",
          "മാലോകര്‍ ആന്ദമോടുണർന്നിതാ",
          "നക്ഷത്തം തൂക്കിയും തോരണങ്ങൾ ചാർത്തിയും",
          "പൂത്തിരികൾ കത്തിച്ചും പൂമരങ്ങൾ ഒരുക്കിയും",
          "നാഥനെ വരവേറ്റിടും (2)",
          "",
          "അങ്ങകലെ ആകാശത്തിൽ",
          "നവതാരം മെല്ലെ ഉദിച്ചു",
          "താരങ്ങൾ മിന്നി തെളിഞ്ഞു",
          "സ്തുതിഗീതം പാടി നിന്നു (2)",
          "",
          "മഞ്ഞുപെയ്യും താഴ്വരയില്‍ ദേവദാരു പൂത്തതും",
          "മറിയത്തിന്‍ മകനാണല്ലോ ഈ സ്നേഹത്തിന്‍ തിരിയാലല്ലോ",
          "ലാ ലാലാലലലാ ലാലാലലലാ ലാലാലലലാ ല ല ലാ (2)",
          "",
          "(പള്ളി മേടയിൽ... )"
        ]
      },
      {
        "slug": "paloolithookia",
        "title": "പാലൊളി തൂകിയ പാതിരാ നേരത്ത്",
        "listLabel": "പാലൊളി തൂകിയ പാതിരാ നേരത്ത്",
        "order": 5,
        "lines": [
          "പാലൊളി തൂകിയ പാതിരാ നേരത്ത്",
          "പാരിതിൽ പിറന്നോനെ",
          "",
          "പാപങ്ങൾ പോക്കണേ",
          "ശാപങ്ങൾ തീർക്കണേ",
          "ധരണിയിൻ  അധിപതിയെ (2)",
          "",
          "കുസുമങ്ങൾ വിടരട്ടെ പരിമളം പരക്കട്ടെ",
          "ശൂന്യപ്രദേശങ്ങൾ ആർത്തിടട്ടെ (2)",
          "ആ ആ ദേവകുമാരാ രാജകുമാര ദാവീദിൻ വംശജനെ",
          "കളങ്കങ്ങൾ കഴുകിടണേ (2)",
          "",
          "(പാലൊളി തൂകിയ ... )",
          "",
          "മയിലുകൾ ആടട്ടെ കുയിലുകൾ പാടട്ടെ",
          "വയലുകൾ കരിവള കിലുക്കിടട്ടെ (2)",
          "ആ ആ ദേവകുമാരാ രാജകുമാര ദാവീദിൻ വംശജനെ",
          "കളങ്കങ്ങൾ കഴുകിടണേ (2)",
          "",
          "(പാലൊളി തൂകിയ ... )"
        ]
      },
      {
        "slug": "patttuvirichamethakal",
        "title": "പട്ടുവിരിച്ച മെത്തകളില്ല",
        "listLabel": "പട്ടുവിരിച്ച മെത്തകളില്ല",
        "order": 11,
        "lines": [
          "പട്ടുവിരിച്ച മെത്തകളില്ല",
          "മന്ദിരമില്ല ശയിപ്പാനായ്",
          "വെറുമൊരു കാലി പുല്ക്കൂടതിലായ്",
          "രക്ഷകനേശു പിറന്നല്ലോ",
          "എൻ രക്ഷകനേശു പിറന്നല്ലോ",
          "",
          "കാലും മേലും നോവുന്നില്ലേ",
          "കമ്പിളി ഇല്ലേ പുതയ്&zwnj;ക്കാനായ്  (2)",
          "",
          "സങ്കടമുണ്ടിതു കാണുമ്പോഴും",
          "തങ്കകുടമേ പൊന്നുണ്ണി (2)",
          "",
          "പൊന്നുണ്ണി നിനക്കെന്തേ",
          "മാനത്തു വസിക്കാതെ",
          "മാളോരെ തേടി നീ",
          "താഴോട്ടു വന്നല്ലോ (2)",
          "",
          "പട്ടുവിരിച്ച മെത്തകളില്ല",
          "മന്ദിരമില്ല ശയിപ്പാനായ്",
          "വെറുമൊരു കാലി പുല്ക്കൂടതിലായ്",
          "എൻ രക്ഷകനേശു പിറന്നല്ലോ (2)"
        ]
      },
      {
        "slug": "poothiri",
        "title": "പൂത്തിരി മത്താപ്പൂ മിന്നി തിളഞ്ഞുന്ന",
        "listLabel": "പൂത്തിരി മത്താപ്പൂ",
        "order": 17,
        "lines": [
          "പൂത്തിരി മത്താപ്പൂ മിന്നി തിളഞ്ഞുന്ന",
          "മംഗള മണി മുഴങ്ങി",
          "വർണ കടലാസു നക്ഷത്ര ദീപങ്ങൾ",
          "ചന്ദത്തിലൊരുങ്ങിയല്ലോ (2)",
          "",
          "പ്രവാചകന്മാരും മുനിമാരും പൊന്നവധാരം പ്രവചിച്ചല്ലോ(2)",
          "ഈലോകം കാണാത്ത പൊൻസുദീനം",
          "എൻ മശിഹ അവധരിച്ചു (2)",
          "",
          "(പൂത്തിരി മത്താപ്പൂ മിന്നി തിളഞ്ഞുന്ന ...)"
        ]
      },
      {
        "slug": "poyidaam-koottare",
        "title": "പോയിടാം കൂട്ടരേ സ്വർല്ലോക നാഥന്റെ",
        "listLabel": "പോയിടാം കൂട്ടരേ",
        "order": 7,
        "lines": [
          "പോയിടാം കൂട്ടരേ സ്വർല്ലോക നാഥന്റെ",
          "ജനനത്തെ ലോകമെങ്ങും ഘോഷിച്ചീടാം (2)",
          "തപ്പുതാള മേളമോടെ ഒത്തുചേർന്നു പാടിടാം",
          "സ്വർഗ്ഗനാഥൻ ഭൂവിൽ വന്ന സുദിനം",
          "പാട്ടു പാടി ഘോഷിച്ചീടാം – ഇന്ന് –",
          "ആർത്തുപാടി ഘോഷിച്ചീടാം (2)",
          "",
          "രാജാധിരാജാവാം ശ്രീയേശുനാഥന്റെ",
          "തൃപ്പാദം കുമ്പിട്ടീടാം (2)",
          "ആമോദരായിന്നു ആനന്ദഗീതികളാൽ",
          "സാമോദം വാഴ്ത്തിപ്പാടാം (2)",
          "(പോയിടാം കൂട്ടരെ...)",
          "",
          "അജപാലകരെല്ലാം ആഹ്ലാദത്താലിന്നു",
          "നാഥനെ സ്തുതിച്ചിടുന്നു (2)",
          "ശാസ്ത്രിമാർ മൂവരും കാഴ്ചകളർപ്പിച്ച്",
          "രാജനെ വന്ദിക്കുന്നു (2)",
          "(പോയിടാം കൂട്ടരെ...)"
        ]
      },
      {
        "slug": "pulkudilil",
        "title": "പുല്‍ക്കുടിലില്‍ കല്‍ത്തൊട്ടിയില്‍",
        "listLabel": "പുൽകുടിലിൽ കൽത്തൊട്ടിലിൽ",
        "order": 8,
        "lines": [
          "പുല്‍ക്കുടിലില്‍ കല്‍ത്തൊട്ടിയില്‍",
          "മറിയത്തിന്‍ പൊന്‍ മകനായ്",
          "പണ്ടൊരു നാള്‍ ദൈവസുതന്‍",
          "പിറന്നതിന്‍ ഓര്‍മ്മ ദിനം (2)",
          "",
          "പോരു മണ്ണിലെ ഇടയന്മാരെ",
          "പാടൂ വിണ്ണിലെ മാലാഖകളേ (2)",
          "പാടും തമ്പുരുവും",
          "കിന്നരവും താളവുമായ് (2)",
          "",
          "(പുല്‍ക്കുടിലില്‍ കല്‍ത്തൊട്ടിയില്‍ ...)",
          "",
          "മെല്‍ഷ്യരും കാസ്പരും",
          "ബെല്‍ത്തസറും വാഴ്ത്തും",
          "രക്ഷകരില്‍ രക്ഷകനാം മിശിഹാ പിറന്ന ദിനം (2)",
          "",
          "പോരു മണ്ണിലെ ഇടയന്മാരെ",
          "പാടൂ വിണ്ണിലെ മാലാഖകളേ (2)",
          "പാടും തമ്പുരുവും",
          "കിന്നരവും താളവുമായ് (2)",
          "",
          "(പുല്‍ക്കുടിലില്‍ കല്‍ത്തൊട്ടിയില്‍ ...)",
          "",
          "ഭൂമിയില്‍ ദൈവമക്കള്‍",
          "നേടും സമാധാനം",
          "ഉന്നതിയില്‍ അത്യുന്നതിയില്‍",
          "ദൈവത്തിനു മഹത്വം (2)",
          "",
          "പോരു മണ്ണിലെ ഇടയന്മാരെ",
          "പാടൂ വിണ്ണിലെ മാലാഖകളേ (2)",
          "പാടും തമ്പുരുവും",
          "കിന്നരവും താളവുമായ് (2)",
          "",
          "(പുല്‍ക്കുടിലില്‍ കല്‍ത്തൊട്ടിയില്‍ ...)"
        ]
      },
      {
        "slug": "sam-sam-sambramay",
        "title": "സം സം സംപ്രമായി",
        "listLabel": "സം സം സംപ്രമായി",
        "order": 10,
        "lines": [
          "സം സം സംപ്രമായി സംഗമിക്കും തിങ്കളായി (2)",
          "നസറായ൯ പശുക്കൂട്ടില്‍ പിറന്നോനെ (2)",
          "പിറന്നോനെ പശുക്കൂട്ടില്‍ താനേ (2)",
          "താരക കൊടിയായി പിറന്നോനെ (2)",
          "",
          "തത്ത മയിലുകള്‍ കുയിലുകള്‍ ആകാശത്തില്‍ (2)",
          "ഓര്‍ത്താടി പാടിടുന്നു ജയമോടെ",
          "അവര്‍ ഓര്‍ത്താടി പാടിടുന്നു ജയമോടെ",
          "",
          "പുത്തനായി - തത്തകള്‍ സ്തുതിയേ (2)",
          "പൂര്‍ത്തിയായി കേട്ടതും അതിശയമേ (2)",
          "",
          "(സം സം സംപ്രമായി ...)",
          "",
          "ആട്ടിടയര്‍ കൂട്ടവും താനെ (2)",
          "കാട്ടിയ വെളിച്ചവും കണ്ടുടനുണര്‍ന്നു (2) ( സം സം)",
          "",
          "(സം സം സംപ്രമായി ...)"
        ]
      },
      {
        "slug": "thaarakamvannidhiche",
        "title": "താരകം വന്നുദിച്ചേ",
        "listLabel": "താരകം വന്നുദിച്ചേ",
        "order": 20,
        "lines": [
          "താ തിനന്തക തെയ്താരോ",
          "തകതിനന്തക തെയ്താരോ",
          "താതിനന്തക തകതിനന്തക",
          "തകതിനന്തക തെയ്താരോ (2)",
          "",
          "താരകം വന്നുദിച്ചേ",
          "അന്നു ബേതലേം പുല്‍ക്കുടിലില്‍",
          "വിദ്വാന്മാർ മൂവരും കാഴ്ചകളുമായ് വന്ന്",
          "നാഥനെ കാണാനെത്തി (2)",
          "",
          "(താ തിനന്തക തെയ്താരോ ... )",
          "",
          "മാലാഖ വൃന്ദമിന്നു",
          "താരാട്ടു പാടിടുമ്പോള്‍",
          "ആഹ്ലാദത്തോടെ നാം കൈകൊട്ടിപ്പാടുക",
          "രക്ഷകന്‍ ജാതനായി (2)",
          "",
          "(താ തിനന്തക തെയ്താരോ ... )",
          "",
          "മഞ്ഞു പെയ്യുന്നീ രാവില്‍",
          "താരം പുഞ്ചിരി തൂകും രാവില്‍,",
          "ആമോദത്തോടെ നാം വാഴ്ത്തിപ്പാടിടുക",
          "രക്ഷകന്‍ ജാതനായി (2)",
          "",
          "(താ തിനന്തക തെയ്താരോ ... )",
          "",
          "ട്യൂൺ : താരക പെണ്ണാളേ സോങ്ങിന്റെ പാരഡി"
        ]
      },
      {
        "slug": "yahoodhiyayille",
        "title": "യഹൂദിയായിലെ ഒരു ഗ്രാമത്തിൽ",
        "listLabel": "യഹൂദിയായിലെ ഒരു ഗ്രാമത്തിൽ",
        "order": 19,
        "lines": [
          "യഹൂദിയായിലെ ഒരു ഗ്രാമത്തിൽ",
          "ഒരു ധനുമാസത്തിൻ കുളിരും രാവിൽ",
          "രാപാര്‍ത്തിരുന്നൊരജപാലകർ",
          "ദേവനാദം കേട്ടു ആമോദരായ്",
          "വര്‍ണ്ണരാജികൾ വിടരും വാനിൽ",
          "വെള്ളിമേഘങ്ങൾ ഒഴുകും രാവിൽ",
          "താരകാ രാജകുമാരിയോടൊത്തന്നു",
          "തിങ്കൾ കലപാടി ഗ്ലോറിയ..",
          "അന്നു തിങ്കൾ കലപാടി ഗ്ലോറിയ..",
          "",
          "താരകം തന്നേ നോക്കീ ആട്ടിടയര്‍ നടന്നു (2)",
          "തേജസ്സു മുന്നിൽക്കണ്ടു അവര്‍",
          "ബേതലേം തന്നിൽ വന്നു (2)",
          "രാജാധിരാജന്റെ പൊൻ‌തിരുമേനി (2)",
          "അവര്‍ കാലിത്തൊഴുത്തിൽക്കണ്ടു",
          "",
          "വര്‍ണ്ണരാജികൾ വിടരും വാനിൽ",
          "വെള്ളിമേഘങ്ങൾ ഒഴുകും രാവിൽ",
          "താരകാ രാജകുമാരിയോടൊത്തന്നു",
          "തിങ്കൾ കലപാടി ഗ്ലോറിയ..",
          "അന്നു തിങ്കൾ കലപാടി ഗ്ലോറിയ..",
          "",
          "മന്നവര്‍ മൂവരും ദാവീദിൻ സുതനേ ..(2)",
          "കണ്ടു വണങ്ങിടുവാൻ അവര്‍ കാഴ്ച്ചയുമായ് വന്നു (2)",
          "ദേവാദിദേവന്റെ തിരുസന്നിധിയിൽ",
          "അവര്‍ കാഴ്ച്ചകൾ വച്ചു വണങ്ങി (2)",
          "",
          "വര്‍ണ്ണരാജികൾ വിടരും വാനിൽ",
          "വെള്ളിമേഘങ്ങൾ ഒഴുകും രാവിൽ",
          "താരകാ രാജകുമാരിയോടൊത്തന്നു",
          "തിങ്കൾ കലപാടി ഗ്ലോറിയ..",
          "അന്നു തിങ്കൾ കലപാടി ഗ്ലോറിയ..",
          "",
          "(യഹൂദിയായിലെ ഒരു ഗ്രാമത്തിൽ ...)"
        ]
      }
    ]
  }
};
